version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: vehicles-api
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - .env.example
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  mongo_data:
